### ISSUE TITLE
How can I integrate this with the admin control panel check?

### ISSUE THREAD

**Issue by FunkyLoveCow** [stewartiee/Steam-OpenID--MyBB-#16]
I wish to grant a couple users that registered via this integration access to the control panel. When they click on `Admin CP`, though, they are presented with a screen requesting Username and Password. 

Can this screen either be linked in to use Steam directly (requiring them to re-signin via Steam Community) or can it be removed entirely since they have validated via Steam they are who they say they are?

**Comment by stewartiee** [comment]
We are in the phase of testing for Version 2. For more information on what's to come, refer to the wiki post. https://github.com/stewartiee/Steam-OpenID--MyBB-/wiki/Version-2-Info
