### ISSUE TITLE
Cant login normally 

### ISSUE THREAD

**Issue by formatme** [stewartiee/Steam-OpenID--MyBB-#31]
on my forum when i click login it takes the way how you login with steam, and its not the normal mybb way.
http://mousefive.com/f/member.php?action=login

**Comment by stewartiee** [comment]
We are in the phase of testing for Version 2. For more information on what's to come, refer to the wiki post. https://github.com/stewartiee/Steam-OpenID--MyBB-/wiki/Version-2-Info
