### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by SurfShackk** [stewartiee/Steam-OpenID--MyBB-#32]
Hi Stewartiee,

I have tried installing the Steam Login and have gotten so far until I have tried to login and all I get is a message "You shouldn't be here" 

Is there something I'm doing wrong? I have installed the necessary plugins of what I can think of and put in the API key. 

Let me know when possible,

Kind Wishes,

// SurfS

**Comment by stewartiee** [comment]
We are in the phase of testing for Version 2. For more information on what's to come, refer to the wiki post. https://github.com/stewartiee/Steam-OpenID--MyBB-/wiki/Version-2-Info
